# Credit: https://github.com/CCCC-L/fcitx5-android/blob/master/.github/workflows/ci.yml
name: Build APK

on:
  workflow_dispatch:

jobs:
  build_apk:
    runs-on: ubuntu-24.04
    env:
      BUILD_ABI: arm64-v8a
    steps:
      - name: Fetch source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android environment
        uses: android-actions/setup-android@v3

      - name: Install Android NDK
        run: |
          sdkmanager --install "cmake;3.31.6"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install extra-cmake-modules gettext

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Release APK
        run: |
          ./gradlew :app:assembleRelease --stacktrace

      - name: Upload app with plugins
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}-${{ matrix.abi }}-with-plugins
          path: app/build/outputs/apk/release/*.apk
